### PR TITLE
Fix crash when setting non-JSON conforming attributes

### LINKED ISSUE #33: Sanitize `Dictionary` Attributes
I'm getting crashes from the SDK when one of the `Dictionary` attributes (extra, tags, etc..) contains something that can't be parsed in JSON (i.e. `NSURL`). We need a way to detect these items and sanitize them, or place a constraint on the dictionary types.

### PR DESCRIPTION
**Pull request by dcvz**
Fixes #33 

This fixes the immediate problem of the app crashing.. however, this should not be the long term fix. We don't convey in any way to the user that the dictionaries they use for extras/tags are supposed to be JSON mappable... it's also bad if users are setting some weird things in their tags and now their events are not being reported because the serialization is failing.

so we should either convey this through a custom type/documentation or we should find a way to sanitize the values. I prefer latter because I find it weird for the user to have to sanitize their own dictionaries. we could also possibly just drop the failing part but still send the event (probably best option as the user would be missing info, but not the whole event)

however, I'd say let's merge this to fix the immediate problem then i can make a PR with a fix (which may take longer)

**Ammend:**
I've now added functionality to where, if one of the tags or extras will fail serialization, we'll just exclude it from the event. That way users will still get alerted about errors; however, it will unfortunately not contain all the info they wanted.

I've also removed the `mergeProperties` method and made tags and extra default to `[:]`. The defaulting tags to `[:]` was because we always run the `mergeProperties` which basically was doing that, defaulting it to `[:]` it's more clear to do it at the model level.

About removing `mergeProperties` I don't think it makes sense to have that be an abstracted part, I think we should manually be merging objects wherever we need to merge them.. (i.e. reportEvent) and it was hard to maintain while fixing the crash problem..

### CODE REVIEW

File: Sources/Event.swift [hunk 1]
```diff
@@ -52,9 +52,9 @@ public typealias EventFingerprint = [String]
 	public var culprit: String?
 	public var serverName: String?
 	public var releaseVersion: String?
-	public var tags: EventTags?
+	public var tags: EventTags = [:]
 	public var modules: EventModules?
-	public var extra: EventExtra?
+    public var extra: EventExtra = [:]
```
Comment (joshdholtz) [inline Sources/Event.swift]: @dcvz Messed up tabbing here 😉

File: SentrySwiftTests/SentrySwiftTests.swift [hunk 2]
```diff
@@ -331,15 +332,18 @@ class SentrySwiftTests: XCTestCase {
...
-        assert(event.extra == nil)
+        assert(event.tags == [:])
+        assert(event.extra == [:])
         assert(event.user == nil)
 
-		event.mergeProperties(from: client)
-        assert(event.tags! == testTags)
-        assert(event.extra! == testExtra)
+		event.tags.unionInPlace(client.tags ?? [:])
+		event.extra.unionInPlace(client.extra ?? [:])
```
Comment (joshdholtz) [inline SentrySwiftTests/SentrySwiftTests.swift]: @dcvz Tabbing also seems messed up here 😇

File: SentrySwiftTests/SentrySwiftTests.swift [hunk 3]
```diff
@@ -348,23 +352,25 @@ class SentrySwiftTests: XCTestCase {
...
 
         event.tags = testTags
         event.extra = testExtra
         event.user = testUser
 
-		event.mergeProperties(from: client)
-        assert(event.tags! == testTags)
-        assert(event.extra! == testExtra)
+		event.tags.unionInPlace(client.tags)
+		event.extra.unionInPlace(client.extra)
```
Comment (joshdholtz) [inline SentrySwiftTests/SentrySwiftTests.swift]: @dcvz One more place 😬

**Comment by joshdholtz** [comment]
@dcvz This looks good to me! If you could fix some of that tabbing I will merge this

**Comment by dcvz** [comment]
Fixed @joshdholtz :)
