### PR TITLE
Event sending in background

### LINKED ISSUE #57: User info is not sent or displayed for a Fatal error
When I track a `Fatal` error, the user info (email and id) is not displayed in the web interface. If I change the severity to `Warning` the user info does show up.

``` swift
let event = Event.build("ErrorTest") {
  $0.level = .Fatal
  $0.tags = [:]
  $0.extra = [:]
  if let file = file, function = function {
    $0.stacktrace = Stacktrace(frames: [Frame(file: file, function: function, line: line)])
  }
}
SentryClient.shared?.captureEvent(event)
```

I am using sentry-swift version **0.3.3**.

### PR DESCRIPTION
**Pull request by HazAT**
- [x] Remove appleCrashReport variable
- [x] Use detail model_id for backend
- [x] Add `versionString` for future usage
- [x] Move as much as possible into simple background threads
- [x] Fix #57

### CODE REVIEW

File: Sources/KSCrashHandler.swift [hunk 1]
```diff
@@ -73,7 +73,9 @@ internal class KSCrashHandler: CrashHandler {
 		
 		// Install
 		installation.install()
-
+        
+        SentryLog.Debug.log("Started Sentry Client \(SentryClient.versionString)")
```
Comment (mitsuhiko) [inline Sources/KSCrashHandler.swift]: Bad indentation
